[package]
name = "ch56_async_api_call"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.4"
reqwest = { version = "0.11.17", features = ["json"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
